"use client";

import { useScrollReveal } from "@/hooks/useScrollReveal";

const problems = [
  {
    title: "The Time Trap",
    desc: "Every hour you sell is an hour you can't scale. Your income has a structural ceiling built in.",
  },
  {
    title: "The Interchangeability Problem",
    desc: "Without strategic positioning, you compete on price. You become replaceable.",
  },
  {
    title: "The Content Illusion",
    desc: "Publishing without a conversion system is creative activity, not a business asset.",
  },
];

const costs = [
  { stat: "∞", desc: "Hours traded for income, with no end in sight" },
  {
    stat: "0",
    desc: "Organic leads generated by your current content system",
  },
  { stat: "1", desc: "Premium offer you could be selling, but aren't" },
];

export default function ProblemSection() {
  const ref = useScrollReveal<HTMLElement>();

  return (
    <section
      ref={ref}
      id="services"
      style={{ background: "var(--bg)", padding: "8rem 3rem" }}
    >
      <div
        style={{
          maxWidth: "1200px",
          margin: "0 auto",
          display: "grid",
          gridTemplateColumns: "55fr 45fr",
          gap: "5rem",
          alignItems: "start",
        }}
      >
        {/* ── Left: The Diagnosis ── */}
        <div>
          <p
            data-reveal
            style={{
              fontSize: "0.7rem",
              color: "rgba(255,255,255,0.35)",
              textTransform: "uppercase",
              letterSpacing: "0.16em",
              marginBottom: "1.5rem",
            }}
          >
            The Real Problem
          </p>

          <h2
            data-reveal
            data-delay="1"
            style={{
              fontSize: "clamp(1.75rem, 3.5vw, 2.75rem)",
              fontWeight: 700,
              letterSpacing: "-0.03em",
              lineHeight: 1.1,
              color: "#fff",
              marginBottom: "3rem",
            }}
          >
            It&rsquo;s not that you lack clients.
            <br />
            It&rsquo;s that you lack positioning.
          </h2>

          {problems.map((p, i) => (
            <div
              key={p.title}
              data-reveal
              data-delay={`${i + 2}`}
              style={{
                borderLeft: "1px solid rgba(255,255,255,0.12)",
                paddingLeft: "1.5rem",
                marginBottom: "2rem",
              }}
            >
              <h3
                style={{
                  fontWeight: 600,
                  color: "#fff",
                  marginBottom: "0.4rem",
                  fontSize: "0.975rem",
                }}
              >
                {p.title}
              </h3>
              <p
                style={{
                  color: "rgba(255,255,255,0.45)",
                  lineHeight: 1.65,
                  fontSize: "0.9rem",
                }}
              >
                {p.desc}
              </p>
            </div>
          ))}

          <hr
            style={{
              border: "none",
              borderTop: "1px solid rgba(255,255,255,0.07)",
              marginTop: "2.5rem",
            }}
          />
        </div>

        {/* ── Right: The Cost ── */}
        <div data-reveal data-delay="2">
          <div
            style={{
              background: "var(--surface)",
              border: "1px solid var(--border-c)",
              borderRadius: "20px",
              padding: "2rem",
            }}
          >
            <h3
              style={{
                fontWeight: 600,
                fontSize: "1rem",
                color: "#fff",
                lineHeight: 1.4,
                marginBottom: "2rem",
              }}
            >
              The opportunity cost of staying where you are
            </h3>

            {costs.map((item, i) => (
              <div
                key={i}
                style={{
                  borderBottom:
                    i < costs.length - 1
                      ? "1px solid rgba(255,255,255,0.06)"
                      : "none",
                  paddingBottom: i < costs.length - 1 ? "1.5rem" : 0,
                  marginBottom: i < costs.length - 1 ? "1.5rem" : "2rem",
                }}
              >
                <div
                  style={{
                    fontSize: "3.25rem",
                    fontWeight: 700,
                    color: "#fff",
                    letterSpacing: "-0.04em",
                    lineHeight: 1,
                    fontFamily: "var(--font-geist-mono)",
                  }}
                >
                  {item.stat}
                </div>
                <div
                  style={{
                    fontSize: "0.875rem",
                    color: "rgba(255,255,255,0.4)",
                    marginTop: "0.4rem",
                    lineHeight: 1.5,
                  }}
                >
                  {item.desc}
                </div>
              </div>
            ))}

            <a
              href="#contact"
              style={{
                fontSize: "0.875rem",
                color: "rgba(255,255,255,0.55)",
                textDecoration: "none",
                transition: "color 0.2s ease",
                display: "inline-block",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.color = "#fff")}
              onMouseLeave={(e) =>
                (e.currentTarget.style.color = "rgba(255,255,255,0.55)")
              }
            >
              Change the equation →
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}
